ecome/core/urls.py
from django.urls import path 
from .views import *


app_name = "core"

urlpatterns = [
     path("",HomeView.as_view(),name="homepage"),
     path("products/<slug>/",ItemDetailsView.as_view(),name="item"),
     path("order-summary/",OrderSummaryVIew.as_view(),name="order-summary"),
     path("checkout/",CheckOutView.as_view(),name="checkout"),
     path("my-order/",myOrder,name="myOrder"),
     path("save-address-action/",save_Address_Action,name="save_Address_Action"),
     path("add-to-cart/<slug>/",AddToCart.as_view(),name="add-to-cart"),
     path("remove-from-cart/<slug>/",RemoveFromCart.as_view(),name="remove-from-cart"),
     path("minus-from-cart/<slug>/",MinusItemCart.as_view(),name="minus-from-cart"),
     path("add-coupon/",AddCouponView.as_view(),name="add-coupon"),
     path("remove-coupon/",RemoveCouponView.as_view(),name="remove-coupon"),
]

ecome/ecome/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("accounts/",include("allauth.urls"))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecome/core/models.py
from enum import unique
from pydoc import describe
from pyexpat import model
from statistics import mode
from tabnanny import verbose
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
######################################################################
class Category(models.Model):
    title  = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField()

    def get_absolute_url(self):
        return reverse("core:category",kwargs={
            'slug':self.slug
        })
    def __str__(self):
        return self.title

#######################################################################   
class Brand(models.Model):
    brand_name = models.CharField(max_length=200)
    slug = models.SlugField()

    def get_absolute_url(self):
        return reverse("core:brand",kwargs={
            'slug':self.slug
        })
    def __str__(self):
        return self.brand_name
#######################################################################
LABEL_CHOICE = (
    ('p',"primary"),
    ('s','secondary'),
    ('d','danger')
)

class Item(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL, null=True,blank=True)
    label = models.CharField(choices=LABEL_CHOICE, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    price = models.FloatField()
    discount_price = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:item", kwargs={"slug": self.slug})
        
        
#######################################################################
class Variation(models.Model):
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    name = models.CharField(max_length=200) #size , color, type, design etc
#######################################################################
class ItemVariation(models.Model):
    variation = models.ForeignKey(Variation,on_delete=models.CASCADE)
    value = models.CharField(max_length=50) #L, M, S, XL, red, yellow, C type, B type
    attachment = models.ImageField(blank=True)

    class Meta:
        unique_together = (
            ('variation','value')
        )

    def __str__(self):
        return self.value
    
########################################################################
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    qty = models.IntegerField(default=1)
    item_variations = models.ManyToManyField(ItemVariation)

    def get_total_price(self):
        return self.qty*self.item.price
    
    def get_total_discount_price(self):
        return self.qty*self.item.discount_price

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()

    def get_saved_amount(self):
        return self.get_total_price() - self.get_final_price()
    
    def total_discount_precentage_price(self):
        return int(100-(self.item.discount_price/self.item.price)*100)
    


########################################################################
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=200)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    address = models.ForeignKey("Address",related_name="shipping_address",on_delete=models.SET_NULL,blank=True,null=True)
    payment = models.ForeignKey("Payment",on_delete=models.SET_NULL,blank=True,null=True)
    coupon = models.ForeignKey("Coupon",on_delete=models.SET_NULL,blank=True,null=True)
    ordered = models.BooleanField(default=False)
    being_delivered = models.BooleanField(default=False)
    recieved = models.BooleanField(default=False)
    refund_required = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        
        if self.coupon:
            total -= self.coupon.amount
        return total 

    def get_total_tax(self):
        total = self.get_total()
        return round(0.18*total)

    def get_total_discount_amount(self):
        total  = 0 
        for order_item in self.items.all():
            total += order_item.get_saved_amount()
        return total
   
    def get_payable_amount(self):
        return self.get_total_tax() +  self.get_total()

    

########################################################################
CITY_CHOICE = (
    ("PR","Purnea"),
    ("PAT","Patna"),
)
STATE_CHOICE = (
    ("BR","Bihar"),
    ("JH","Jharkhand"),
)
ADDRESS_CHOICE = (
    ("H","Home"),
    ("O","Office"),
)

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    contact = models.IntegerField()
    pincode = models.IntegerField()
    locality = models.CharField(max_length=200)
    street_address = models.TextField()
    city = models.CharField(choices=CITY_CHOICE, max_length=20)
    state = models.CharField(choices=STATE_CHOICE, max_length=20)
    landmarks=  models.CharField(max_length=200,blank=True,null=True)
    alternative_no = models.IntegerField(blank=True,null=True)
    address_type = models.CharField(choices=ADDRESS_CHOICE, max_length=1)
    default= models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Addresses"

#######################################################################
class Payment(models.Model):
    txt_id = models.CharField(max_length=400)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

########################################################################
class Coupon(models.Model):
    code = models.CharField(max_length=200)
    amount = models.FloatField()

    def __str__(self):
        return self.code
    
########################################################################
class Refund(models.Model):
    order  = models.ForeignKey(Order,on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"
    
#######################################################################

ecome/core/forms.py
from dataclasses import fields
from .models import Address
from tkinter import Widget

from django import forms 

class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class':"form-control",
        'placeholder' : "Promo Code",
}))

class CheckoutForm(forms.ModelForm):
    class Meta:
        model  = Address
        exclude = ["user",]

ecome/core/views.py
import random
import string 
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,DetailView,View

from .forms import CouponForm, CheckoutForm
from .models import Address, Coupon, Item, ItemVariation,OrderItem,Order, Payment, Variation
from django.utils import timezone
class HomeView(ListView):
    model = Item
    paginate_by = 10
    template_name = "home.html"




class ItemDetailsView(DetailView):
    model = Item
    template_name = "product.html"
    slug_url_kwarg = "slug"

    def get_context_data(self,*args, **kwargs):
        context = super(ItemDetailsView,self).get_context_data(*args,**kwargs)
        context['items'] = Item.objects.exclude(slug=self.kwargs['slug'])
        return context

class RemoveFromCart(LoginRequiredMixin,View):
    def get(self,request,slug,*args, **kwargs):
        item = get_object_or_404(Item,slug=slug)

        order_qs = Order.objects.filter(user=request.user,ordered=False)
        
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item = OrderItem.objects.filter(item=item,user=request.user,ordered=False)[0]
                order.items.remove(order_item)
                order_item.delete()
            
            return redirect("core:order-summary")
            
class AddToCart(LoginRequiredMixin,View):
    def get(self,request,slug,*args, **kwargs):
        item = get_object_or_404(Item,slug=slug)

        order_item, created = OrderItem.objects.get_or_create(
            item=item,
            user=request.user,
            ordered=False
        )
        # for varient
        var = []

        varient = Variation.objects.filter(item=item)

        for v in varient:
            var.append(request.GET.get(v.name, None))

        order_qs = Order.objects.filter(user=request.user,ordered=False)
        
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item.qty += 1
                order_item.save()
                return redirect("core:order-summary")
            else:
                order.items.add(order_item)
                for v in var:
                    a = ItemVariation.objects.get(value=v, variation__item__slug=item.slug)
                    order_item.item_variations.add(a)
                return redirect("core:order-summary")

        else:
            ordered_date = timezone.now()
            order = Order.objects.create(user=request.user,start_date=ordered_date)
            order.items.add(order_item)
            return redirect("core:order-summary")


            
class MinusItemCart(LoginRequiredMixin,View):
    def get(self,request,slug,*args, **kwargs):
        item = get_object_or_404(Item,slug=slug)

        order_item, created = OrderItem.objects.get_or_create(
            item=item,
            user=request.user,
            ordered=False
        )
        # for varient
        var = []

        varient = Variation.objects.filter(item=item)

        for v in varient:
            var.append(request.GET.get(v.name, None))

        order_qs = Order.objects.filter(user=request.user,ordered=False)
        
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                if order_item.qty > 1:
                    order_item.qty -= 1
                    order_item.save()
                else: 
                    order.items.remove(order_item)

                return redirect("core:order-summary")

        else:
         
            return redirect("core:order-summary")



class OrderSummaryVIew(LoginRequiredMixin,View):
    def get(self, *args, **kwargs):
        try: 
            order = Order.objects.get(user=self.request.user,ordered=False)
            if order.items.count() < 1:
                return redirect("core:homepage")
            context = {"object":order,"couponform":CouponForm}
        except ObjectDoesNotExist:
            return redirect("core:homepage")

        return render(self.request,"order-summary.html",context)
        
    model = Order 
    template_name = "order_summary.html"

def check_coupon(request,code):
    try:
        coupon = Coupon.objects.get(code=code)
        return True
    except ObjectDoesNotExist:
        return False
    
def getCoupon(request,code):
    try: 
        coupon = Coupon.objects.get(code=code)
        return coupon
    except ObjectDoesNotExist:
        return redirect("core:order-summary")
class AddCouponView(View):
    def post(self,*args, **kwargs):
        if self.request.method == "POST":
            form = CouponForm(self.request.POST or None)
            if form.is_valid():
                try:
                    code = form.cleaned_data.get("code")
                    if check_coupon(self.request,code):
                        print("check don")
                        order = Order.objects.get(user=self.request.user,ordered=False)
                        order.coupon = getCoupon(self.request,code)
                        order.save()
                        return redirect("core:order-summary")
                    else: 
                        # if invalid code
                        return redirect("core:order-summary")
                except ObjectDoesNotExist:
                    # invalid cart order
                    return redirect("core:order-summary")
class RemoveCouponView(View):
    def get(self,*args, **kwargs):          
        order = Order.objects.get(user=self.request.user,ordered=False)
        order.coupon = None
        order.save()
        return redirect("core:order-summary")

class CheckOutView(View):

    def get(self,*args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user,ordered=False)
            form  = CheckoutForm()
            address = Address.objects.filter(user=self.request.user)
            return render(self.request,"checkout.html",{"order":order,"forms":form,"address":address})
        
        except ObjectDoesNotExist:
            return redirect("core:checkout")
    
    
    def post(self, *args, **kwargs):
        if self.request.method=="POST":
            order = Order.objects.get(user=self.request.user,ordered=False)
            form= CheckoutForm(self.request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = self.request.user
                data.save()
                order.address = data
                order.save()
                makePayment(self.request)
                return redirect("core:checkout")
            else:
                return redirect("core:checkout")
        else:
            return redirect("core:checkout")

def save_Address_Action(r):
    if r.method == "POST":
        order = Order.objects.get(user=r.user,ordered=False)
        save_address = r.POST.get("save_address",None)
        selected_address = Address.objects.get(id=save_address)
        order.address = selected_address
        order.save()
        makePayment(r)
        return redirect("core:myOrder")


def create_ref_code():
    return "".join(random.choices(string.ascii_lowercase + string.digits, k=20))

def makePayment(r):
    order = Order.objects.get(user=r.user,ordered=False)
    payment = Payment()
    payment.txt_id = "332334252423"
    payment.user = r.user
    payment.amount = order.get_payable_amount()
    payment.save()
#  assign payment to order
    order_item = order.items.all()
    order_item.update(ordered=True)
    order.ordered = True
    order.payment = payment 
    order.ref_code = create_ref_code()
    order.save()
    return redirect("core:myOrder")


def myOrder(r):
    order = Order.objects.filter(user=r.user,ordered=True)
    return render(r,"myorder.html",{"order":order})

ecome/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce | bas Bech do</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a href="" class="navbar-brand">Ecom</a>
        <form action="" class="d-flex">
            {% csrf_token %}        
            <input type="search" name="search" class="form-control">
            <input type="submit" name="find" class="btn btn-success ms-2">
        </form>

        <ul class="navbar-nav mt-1">
            <li class="nav-item"><a href="" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="" class="nav-link">About</a></li>
            <li class="nav-item dropdown">
                <a href="" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Profile</a>

                <div class="dropdown-menu">
                    <a href="" class="dropdown-item">My Profile</a>
                    <a href="" class="dropdown-item">My Order</a>
                    <a href="" class="dropdown-item">Settings</a>
                    <a href="" class="dropdown-item">Logout</a>
                </div>
            </li>
            <li class="nav-item"><a href="{%url 'core:order-summary'%}" class="btn btn-dark position-relative">cart

                <span class="position-absolute top-0 small start-100 border border-light translate-middle badge rounded-pill bg-danger">
                    1
                  </span>
            </a></li>
        </ul>

    </div>
    </nav>


    {% block content %}{% endblock %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

ecome/core/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <h2>Checkout Form</h2>

        <div class="row">
            <div class="col-6">
              <div class="row">
                  <div class="col-12">
                   <form action="{% url 'core:save_Address_Action' %}" method="post">
                       {% csrf_token %}
                       {% for add  in  address %}
                       <div class="mb-3 bg-light">
                           <input type="radio" class="btn-check" name="save_address" value={{add.id}} id="add{{forloop.counter}}" autocomplete="off">
                           <label class="btn btn-outline-secondary w-100" for="add{{forloop.counter}}">
                               <h6>{{add.name}} - {{add.contact}}</h6>
                               <p class="m-0">{{add.locality}} {{add.get_city_display}} {{add.get_state_display}}</p>
                               <p class="m-0">pincode:{{add.pincode}}</p>
                           </label>
                         </div>
                         {% endfor %}
                         <div class="mb-3">
                             <input type="submit" name="save_address_btn" class="btn btn-success" value="Payment">
                         </div>
                   </form>
                    
                  </div>
              </div>
            </div>
            <div class="col-6">
                <div class="card bg-light">
                    <div class="card-body">
                        <form action="" method="post">

                            {% csrf_token %}
                            {{forms|crispy}}
                               
                           <div class="mb-3">
                               <input type="submit" class="btn btn-success float-end" value="Save Address & Payment">
                           </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    </div>

{% endblock  %}

ecome/core/templates/home.html
{% extends 'base.html' %}



{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <div class="row">
                   {% for item in object_list %}
                   <div class="col-3">
                        <div class="card shadow mt-3">
                            <img src="{{item.image.url}}" style="height:300px;" alt="" class="card-img-top">
                            <div class="card-body">
                                <h6>{{ item.get_category_display }}</h6>
                                <h6>
                                    <a href="{{ item.get_absolute_url }}" class="text-truncate text-decoration-none text-dark text-capitalize">{{item.title}}</a>
                                </h6>
                            </div>
                        </div>
                    </div>
                   {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

ecome/core/templates/order-summary.html
{% extends 'base.html' %}


{% block content %}

    <div class="container-fluid g-5">
        <div class="row mt-5 ">
            <div class="col-8">
                {% for order_item in object.items.all  %}
                    <div class="media d-md-flex shadow p-2 d-block mt-3">
                        <img src="{{order_item.item.image.url}}" width="120px" class="media-image d-block shadow"  alt="">

                        <div class="media-body ps-3">
                            <h5 class="mt-1 fw-bolder">{{order_item.item.title}}</h5>
                           <span class="d-block">
                                {% if order_item.item_variations.exists %}
                                    {% for foo in order_item.item_variations.all  %}
                                        <small class="text-muted">{{foo.variation.name}} : {{foo.value}}</small>
                                    {% endfor %}
                                {% endif %}
                           </span>
                        <span class="d-block my-2">
                            {% if order_item.item.discount_price %}
                                <p class="text-dark h5 fw-bold d-inline">₹{{order_item.get_total_discount_price}}</p>
                                <p class="text-muted h5 fw-normal d-inline"><del>₹{{order_item.get_total_price}}</del></p>
                                <p class="text-success fw-bold">Total Saved: ₹{{order_item.get_saved_amount}} ({{order_item.total_discount_precentage_price}}%)</p>
                            {% else %}
                                <p class="text-muted h5 fw-normal d-inline">₹{{order_item.item.price}}</p>
                            {% endif %}
                        </span>
                        <span class="d-block my-2">
                            <a href="{% url 'core:minus-from-cart' order_item.item.slug %}" class=" btn btn-danger fw-bolder">-</a>
                            <span class="">{{order_item.qty}}</span>
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}" class=" btn btn-success fw-bolder">+</a>
                        </span>

                        <div class="d-inline-block">
                            <a href="{% url 'core:remove-from-cart' order_item.item.slug %}" class="btn btn-secondary float-end">Remove</a>
                        </div>
                        </div>
                        
                    </div>
                {% endfor %}
            </div>
            <div class="col-4">
                <h3 class=" display-6">Price Breakpoint</h3>
                <div class=" list-group">
                    <div class="list-group-item list-group-item-action">
                        <span class="fw-bold">Total Amount</span>
                        <span class="float-end">₹{{object.get_total}}</span>
                    </div>
                    <div class="list-group-item list-group-item-action">
                        <span class="fw-bold">Tax GST(18%)</span>
                        <span class="float-end">₹{{object.get_total_tax}}</span>
                    </div>
                  {% if object.get_total_discount_amount > 0.0 %}
                  <div class="list-group-item list-group-item-action bg-success text-white">
                    <span class="fw-bold">Total Discount</span>
                    <span class="float-end">₹{{object.get_total_discount_amount}}</span>
                </div>
                {% endif %}
                
                  {% if object.coupon %}
                  <div class="list-group-item list-group-item-action bg-warning text-white">
                    <span class="fw-bold">Coupon Discount</span>
                    <span class="float-end">₹{{object.coupon.amount}}</span>
                </div>
                  {% endif %}
                    <div class="list-group-item list-group-item-action display-6">
                        <span class="fw-bold">Total Payable</span>
                        <span class="float-end small">₹{{object.get_payable_amount}}</span>
                    </div>
                </div>

                {% if object.coupon %}
                    <h2 class="h6 text-center mt-2">{{object.coupon.code}} already Applied <a href="{% url 'core:remove-coupon' %}" class="btn btn-info">Remove</a></h2>
                {% else %}
                <div class="card mt-3">
                    <div class="card-body">
                        <form action="{% url 'core:add-coupon' %}" method="post" class="d-flex">
                            {% csrf_token %}
                            {{couponform.code}}
                            <input type="submit" class="btn btn-success" value="Go">
                        </form>
                    </div>
                </div>
                {% endif %}


                <div class="row mt-5">
                    <div class="col">
                        <a href="" class="btn btn-success w-100">Continue Shopping</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'core:checkout'%}" class="btn btn-warning w-100">Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock  %}

ecome/core/templates/product.html
{% extends 'base.html' %}



{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <div class="row">
                   <div class="col-3">
                        <img src="{{object.image.url}}"  alt="" class="card-img-top">
                   </div>
                    <div class='col-9'>
                        <div class="card shadow">
                            <div class="card-body">
                                <h6>{{ object.title }}</h6>
                                <h6>{{ object.category }}</h6>
                                <h6>Rs.{{ object.discount_price }}</h6>
                                <h6><del>Rs.{{ object.price }}</del></h6>
                               <a href="" class="btn btn-success">Buy Now</a>
                               <form action="{% url 'core:add-to-cart' object.slug %}">
                                   {% for foo in object.variation_set.all %}
                                        <p>{{foo.name}}</p>
                                        {% for val in foo.itemvariation_set.all %}
                                            <input type="radio" class="form-check-input" value="{{val.value}}" name="{{foo.name}}" required/>
                                            <label for="" class="form-check-label">{{val.value}}</label>

                                        {% endfor %}
                                   {% endfor %}
                                <input type="submit" value="Add To Cart" class="btn btn-primary mt-1">
                                </form> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <div class="row">
                   {% for item in items %}
                   <div class="col-3">
                        <div class="card shadow">
                            <img src="{{item.image.url}}" style="height:300px" alt="" class="card-img-top">
                            <div class="card-body">
                                <h6>{{ item.get_category_display }}</h6>
                                <h6>
                                    <a href="{{ item.get_absolute_url }}" class="text-truncate text-decoration-none text-dark text-capitalize">{{item.title}}</a>
                            
                                </h6>
                            </div>
                        </div>
                    </div>
                   {% endfor %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}